language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpcs